### ISSUE TITLE
Halo regions from the beginning?

### ISSUE THREAD

**Issue by ali-ramadhan** [thabbott/JULES.jl#15]
Do we want to support halo regions from the start?

If so [OffsetArrays.jl](https://github.com/JuliaArrays/OffsetArrays.jl) might be useful.

Ignoring the messy question of how to implement boundary conditions, we found using halo regions significantly simplifies the spatial operators as the x, y, z operators can be made to all look the same.

**Comment by thabbott** [comment]
![image](https://user-images.githubusercontent.com/11680078/65461874-a3cebc80-de22-11e9-81d9-f2800071d2d5.png)

**Comment by ali-ramadhan** [comment]
The perfect expression in response to halo regions!

Closing as answer is obvious, and you're already using OffsetArrays on your branch.
