### ISSUE TITLE
AppVeyor code coverage

### ISSUE THREAD

**Issue by thabbott** [thabbott/JULES.jl#18]
The AppVeyor build keeps failing while trying to detect coverage statistics---see e.g. [this build](https://ci.appveyor.com/project/thabbott/jules-jl/build/job/0xy9dr7g20t23drw). Since the Travis builds successfully report coverage should we just have the AppVeyor build run tests but not detect and report coverage?

**Comment by ali-ramadhan** [comment]
Hmmm yeah that's weird. Seems that it fails if any coverage file is missing but Julia does not produce a coverage file for files that have zero coverage.

Could probably fix this but also a good idea to disable and just have one CI pipeline be responsible for reporting code coverage. Appveyor is useful for Windows testing.
