### ISSUE TITLE
Some comments, suggestions, and typos on the algorithm notes

### ISSUE THREAD

**Issue by ali-ramadhan** [thabbott/JULES.jl#20]
Been reading the algorithm notes and had some comments. Feel free to ignore any super pedantic points.

I'm looking at `algorithm.pdf` at this particular commit: https://github.com/thabbott/JULES.jl/blob/b884c353830a60d85283570da76c66bb10dcd9f7/notes/algorithm.pdf

1. The prognostic variable is not momentum, but momentum per unit volume right?

2. The index gymnastics identities given on page 1 aren't really used, should we still keep them?

3. Should we add Coriolis terms (2Ω×u or f×u) to equations (2)-(4)?

4. Could probably condense equations (2)-(4) into a single equation using `u_i`, `\tau^{(i)}` (or tensor `\tau`), and adding a unit vector to the buoyancy term if we want to. This would also get rid of the Cartesian-looking derivatives so the equation remains coordinate-independent with summation notation. Also, do we want to include forcing terms here?

5. Equation (5) is an empty equation.

6. Might be good to define specific entropy as the entropy per unit mass? Also what `s_0`, `c_v`, `T_0`, `R`, and `\rho_0` are. Maybe this isn't the right time to make the documentation more accessible though.

7. Should we include the equation for arbitrary tracers in section 1, equations (6)-(10)? Presumably they satisfy an advection-diffusion equation like the conservation law defined at the beginning of section 1 plus a forcing term? Is it common to run with arbitrary tracers in the atmosphere for e.g. gas concentrations? I guess in the ocean it's mostly used for biogeochemical tracers.

8. More of a question but are J, τ, and ϵ all given by all SGS turbulence closures? I'm only familiar with LES closures but they usually employ eddy viscosity and eddy diffusivity models and give τ via an eddy viscosity and presumably J through an eddy diffusivity. Do they give ϵ? That seems more something that comes out of a k-ϵ turbulence closure.

9. In section 2, seems confusing to use R to refer to the right-hand-side as R is already used as the specific gas constant in the definition of specific entropy. We also have the same problem... MITgcm uses G to refer to the RHS, which seems a little cryptic...

10. Equation set integrated on the acoustic time steps (page 3) needs minus signs on ∂y(p′) and ∂z(p′).

11. δτ for small acoustic time step might be confusing as it implies infinitesimal to me. Why not use Δτ like Klemp et al. (2007)? I also like their superscript primes, but it's definitely tricky notation.

12. Equation (12) should have a -∂y(p′) not -∂x(p′).

13. I wonder if superscript `n` is better than superscript `t` to indicate a discrete time. `t` is usually used for continuous time. I guess Klemp et al. (2007) use superscript `t`. Depends if we want to consistent with their notation.

14. On page 1, specific entropy is defined with an R, which changes to a `c_p` in section 2.1. Defining `R_specific = c_p - c_v` might make this clearer.

15. Seems to me that linearization is not neccessary to solve for p' analytically. Just curious why it's being done.

**Comment by thabbott** [comment]
Thanks! Useful suggestions, and I think it's probably better to put answers to the questions in the notes then here, so I'll let you know when there are answers there.

**Comment by ali-ramadhan** [comment]
This issue (and the notes) are probably somewhat out of date since your changed the equation set JULES is solving for so I'm closing this issue.
