### ISSUE TITLE
Still any interest?

### ISSUE THREAD

**Issue by ali-ramadhan** [thabbott/JULES.jl#4]
Hey @thabbott and @RaphaelRR, been thinking about this project recently as there's no atmospheric LES model in Julia (or any GPU-enabled one although I may be wrong here) so I think it's a chance to make something easy to use and very useful. As well as tackle some cool research problems that would be within reach with such a code.

MIT is getting a [pretty big GPU cluster](https://researchcomputing.mit.edu/satori) at the end of the month so we should have plenty of local resources.

It's definitely a time-consuming project, and may be difficult to carry out as a side project though. Might be good to be realistic if the time commitment is too large. But we should discuss if there's still any interest, I have some ideas.

**Comment by ali-ramadhan** [comment]
@thabbott and I discussed a little bit on Friday and think there should be an approach we can take that allows us to focus on the exciting/interesting work of developing and atmospheric model from scratch.

@thabbott @RaphaelRR are you free this week to meet up?

GitHub probably isn't the best platform for scheduling meetings. We can do this over email.

**Comment by RaphaelRR** [comment]
Yes!!!!!!
