### ISSUE TITLE
Differentiate between potential temperature and modified potential temperature?

### ISSUE THREAD

**Issue by ali-ramadhan** [thabbott/JULES.jl#48]
So far we haven't really done any moist simulations so the prognostic temperature called `ModifiedPotentialTemperature` is really just potential temperature.

With moisture added Klemp et al. (2007) define a "modified potential temperature" that's a little different from virtual temperature.

I wonder if we should have both `PotentialTemperature` (used in dry atmospheres) and a `ModifiedPotentialTemperature` (used when moist species are present) that the user should pick from.

**Comment by thabbott** [comment]
The Klemp modified potential temperature is the same as potential temperature if the atmosphere is dry so I don't think we need to add a separate `PotentialTemperature` *unless* you want to also give users the option of using plain potential temperature in simulations. (But my feeling is that it's probably going to make life easier for us if we develop the model initially with a smaller number of options for the prognostic thermodynamic variable.)

**Comment by ali-ramadhan** [comment]
That's a good point. Might as well just stick with `ModifiedPotentialTemperature` to keep things simpler for now.

Also, I should probably change the model property name `prognostic_temperature` to `thermodynamic_variable`.
