### ISSUE TITLE
Thermodynamic reference states need re-organizing

### ISSUE THREAD

**Issue by thabbott** [thabbott/JULES.jl#55]
The way we're diagnosing temperature and pressure from entropy assumes that all massive tracers have an entropy defined with the same reference temperature, but the way that reference states are stored (one for each massive tracer) doesn't enforce that, since each massive tracer has its own reference temperature. (This is something we could address when we add support for massive tracers that aren't non-condensible ideal gases, since this will require some substantial additions to the model thermodynamics.)

**Comment by ali-ramadhan** [comment]
Ah this isn't stuff I'm familiar with but would like to learn more about.

If it involves substantial refactoring, then maybe we can draft some API/abstraction ideas and pair program them in together.
