### ISSUE TITLE
Account for bulk viscosity

### ISSUE THREAD

**Issue by ali-ramadhan** [thabbott/JULES.jl#58]
We should probably be including the effects of the bulk viscosity in the momentum equation: the ⅓μ∇(∇⋅u) term.

See: https://en.wikipedia.org/wiki/Navier%E2%80%93Stokes_equations#Compressible_flow

Probably doesn't matter for the simpler verification tests we've carried out. Also not sure if it's included (or accounted for) with LES. Will have to investigate more.

**Comment by thabbott** [comment]
I added this when I was working on the n-gas model, actually. I'll link to
a relevant commit once I push one.
