### ISSUE TITLE
Abstraction for velocity fields without extra memory allocations

### ISSUE THREAD

**Issue by ali-ramadhan** [thabbott/JULES.jl#59]
Right now getting velocity is a little clunky as you have to do something like

```julia
model.momenta.ρu[i, j, k] / model.density[i, j, k]
```

Would be nice to have an abstraction for velocity fields like
```julia
struct LazyVelocityField
    momentum:: Field
    density :: Field
end

getindex(A::LazyVelocityField, inds...) = A.momentum[i, j, k] / A.density[i, j, k]
```
then we can just write `model.velocities.u[i, j, k]` and it'll lazily calculate the velocity.

The powerful feature (besides zero memory allocations) is that we can pass this lazy velocity field around to operators and other functions just like a regular field.

Could also use it to tracers (instead of mass-weighted tracer densities [?] if that's fields like ρθ are called) and it could replace the use of functions like `U_over_ρ` and `C_over_ρ`.

**Comment by thabbott** [comment]
This seems great to me! Another option for the type name could be `LazyPrimitiveField` to align with jargon that CFDers use (they e.g. ρu and ρs "conservative variables" and u and s "primitive variables). We'll have to be a little careful about designing the type so that it does the sensible thing (whatever that it) for conservative variables stored at cell center vs. different cell faces but that seems easy enough.

**Comment by ali-ramadhan** [comment]
Ah true so I think we can dispatch on the field location via something like
```julia
struct LazyPrimitiveField{LX, LX, LY} <: AbstractField{LX, LY, LZ}
    momentum :: Field
    density  :: Field
end

getindex(A::LazyVelocityField{Cell, Cell, Cell}, I...) = A.momentum[I...] / A.density[I...]
getindex(A::LazyVelocityField{Face, Cell, Cell}, I...) = A.momentum[I...] / ℑxᶠᵃᵃ(I..., grid, A.density)
```

**Comment by thabbott** [comment]
It'd be useful to have a more general version of this for other things, too, like operations that need total density or entropies of specific species. (And it might also be nice to be able to choose between caching and non-caching versions, the former of which uses memory to store results for re-use, and the latter of which saved memory by re-calculating values every time they're needed.)
