### ISSUE TITLE
Implement time stepper

### ISSUE THREAD

**Issue by thabbott** [thabbott/JULES.jl#7]
(based on meeting on 9/16)

**Comment by ali-ramadhan** [comment]
Some options for Runge-Kutta (RK) time-stepping methods.

1. Vanilla RK3 [originally used by [Wicker & Skamarock (2002)](https://journals.ametsoc.org/doi/full/10.1175/1520-0493%282002%29130%3C2088%3ATSMFEM%3E2.0.CO%3B2)].

Probably a good idea to implement a simple vanilla scheme that we know works well for compressible models and works well with the time-splitting scheme we want to implement. Still used as of March 2019 by the WRF Model Version 4 according to the manual so it must be pretty reliable.

We probably shouldn't implement anything else until we have a working model, but will be good to keep the code flexible enough so we can easily switch time steppers.

I'll implement this and write some simple tests.

---

**Documenting for the future:**

To maximize GPU efficiency by reducing register and memory usage we might want to implement a low-storage Runge-Kutta (LSRK) method.

[Kennedy et al. (2000)](https://www.sciencedirect.com/science/article/abs/pii/S0168927499001415) describe many LSRK schemes for the compressible Navier-Stokes equations.

2. Three-stage, third-order: RK3(2)3[2R+] or four-stage, third-order: RK3(2)4[2R+]

These RK3 schemes might be able to easily replace the vanilla scheme.

3. Five-stage, fourth-order: RK4(3)5[2R+] or six-stage, fourth-order: RK4(3)6[2R+]

If we want to try going up to RK4. Not sure if this will work well with the time-splitting method?

Getting super fancy but the CliMA devs at NPS seem to like these LSRK schemes by [Niegemann et al. (2012)](https://www.sciencedirect.com/science/article/pii/S0021999111005213) as they have optimized stability regions for advection-dominated problems allowing for longer time steps. But these schemes seem to have been tested with discontinuous Galerkin numerics so might not be worth pursuing with finite-volume as the other options seem pretty good.

4. 12, 13, or 14-stage fourth-order LSRK

**Comment by ali-ramadhan** [comment]
The RK3 time stepper described in Klemp et al. (2007) and the WRF Model Version 4 manual has been implemented and tested in #31 and #32 so I'm marking this issue as being resolved.
