### ISSUE TITLE
Generalized split-explicit time-stepping

### ISSUE THREAD

**Issue by ali-ramadhan** [thabbott/JULES.jl#8]
I've seen people talking about [Knoth & Wensch (2014)](https://journals.ametsoc.org/doi/full/10.1175/MWR-D-13-00068.1) recently as a nice alternative to Wicker-Skamarock time-stepping. They report being able to take time steps 4 times as large which seems pretty impressive (although not sure if they came up with this for turbulent 3D flows).

I think they just replace they generalize the method so you can pick something else for the fast integrator, and they suggest a bunch of multirate infinitesimal step (MIS) methods.

Probably not something we want to implement until we have a working model and time to explore, but might be a good idea to keep the code flexible enough to switch between fast integrators.

**Comment by thabbott** [comment]
Agreed--I'll keep this in mind while working on #6

**Comment by ali-ramadhan** [comment]
Closing this issue since current time-stepping scheme is pretty good (just needs an acoustic time stepper) and we should probably implement many other things first.
