### ISSUE TITLE
Should we use PkgTemplates.jl to boostrap a Julia package?

### ISSUE THREAD

**Issue by ali-ramadhan** [thabbott/JULES.jl#9]
https://github.com/invenia/PkgTemplates.jl

It'll generate all the files we need and set up YAML configuration files for CI testing (Travis, Appveyor, etc.) that should come in handy.

**Comment by thabbott** [comment]
Yes, this seems like a good idea. I'll link to repo to travis, appveyor, and codecov.

**Comment by ali-ramadhan** [comment]
I can do it, looks like a pretty neat package, unless someone else wants to get a feel for how Julia packages work.

**Comment by thabbott** [comment]
All clear from me--I've set up Julia packages before.
